### ISSUE TITLE
Error in start_index:nrow(data) : result would be too long a vector

### ISSUE THREAD

**Issue by inregards2pluto** [katy-frank/CTD-processing#1]
Hey, just tried to run the script using the data in the G:\Shared drives\HABs 2023\ERIE WEEKLY\CTD\20230515_WE and encountered this error:

`Error in start_index:nrow(data) : result would be too long a vector`

[global_parameters.csv](https://github.com/katy-frank/CTD-processing/files/11499583/global_parameters.csv)
[station_details.csv](https://github.com/katy-frank/CTD-processing/files/11499584/station_details.csv)
[20230515_WE.zip](https://github.com/katy-frank/CTD-processing/files/11499690/20230515_WE.zip)

**Comment by katy-frank** [comment]
It looks like for WE12 (cast # 35), there were no depth values < 0, so when the script tried to trim those values off the top, it was trying to access the data vector at index -Inf. I have now added a check for that case so that it will work when there are no negative depth values to strip out.
